//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutfitsApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Accessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessory()
        {
            this.Outfits = new HashSet<Outfit>();
        }

        public int AccessoriesID { get; set; }
        [DisplayName("Brand")]
        public string AccessoryBrand { get; set; }
        [DisplayName("Style")]
        public string AccessoryStyle { get; set; }
        [DisplayName("Color")]
        public string AccessoryColor { get; set; }
        [DisplayName("Season")]
        public string AccessorySeason { get; set; }
        [DisplayName("Occasion")]
        public string AccessoryOccasion { get; set; }
        [DisplayName("")]
        public string AccessoryPhoto { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
