//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutfitsApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Bottom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bottom()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int BottomID { get; set; }
        [DisplayName("Brand")]
        public string BottomBrand { get; set; }
        [DisplayName("Style")]
        public string BottomStyle { get; set; }
        [DisplayName("Season")]
        public string BottomSeason { get; set; }
        [DisplayName("Occasion")]
        public string BottomOccasion { get; set; }
        [DisplayName("")]
        public string BottomPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
